### ISSUE TITLE
Cannot pass env variables from the zull config

### ISSUE THREAD

**Issue by 4n4nd** [thoth-station/zuul-config#87]
zuul cannot find the env variables set in the zuul config, but all the gates run.

**To Reproduce**
```- project:
    check:
      jobs:
        - "thoth-coala"
        - thoth-pytest:
            vars:
              PROM_URL: "http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"

    gate:
      queue: "aicoe/prometheus"
      jobs:
        - "thoth-coala"
        - thoth-pytest:
            vars:
              PROM_URL: "http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"
    kebechet-auto-gate:
      queue: "aicoe/prometheus"
      jobs:
        - "thoth-coala"
        - thoth-pytest:
            vars:
              PROM_URL: "http://prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/"
```
A zuul config which runs all the tests, but the `vars` are not seen by the pytests

**Expected behavior**
Run all the gates but the thoth pytest gate should run with the `vars` passed in the zuul config

**Additional context**
The issue I am facing can be seen in this [PR](https://github.com/AICoE/prometheus-api-client-python/pull/58)

**Comment by harshad16** [comment]
Zuul project vars and jobs vars are present in hostvars of ansible.
Using hostvars.pod we can get all the variable including the job vars and project vars.
Explicitly getting these variables in general case is not convenient.
Passing all the vars to Pytest environment. Hence env var pytest can be placed in job variable or pytest variable.

References:
https://zuul-ci.org/docs/zuul/user/jobs.html#job-variables

@goern  @fridex  Just for future references
