### ISSUE TITLE
Comment log output from tests if failed

### ISSUE THREAD

**Issue by 4n4nd** [thoth-station/zuul-config#90]
**Is your feature request related to a problem? Please describe.**
People outside of the org, when try to contribute to our projects and create PRs, can't see the log output from the bots.
Example: https://github.com/AICoE/prometheus-anomaly-detector/pull/78

**Describe the solution you'd like**
Maybe zuul can comment the log output from coala in the PR and also pytest logs if it is not a security issue.

**Describe alternatives you've considered**
Otherwise I have to tell the contributor what the errors are, which causes a lot of delay

**Comment by goern** [comment]
We will have a look if we can host Zuul on the public internet....

**Comment by goern** [comment]
this will be superseded by tekton outputs...
